### ISSUE TITLE
White screen after resuming 

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-conference-app#156]
**Steps:**
1 - Open the app.
2 - Tap back button until the app is closed.
3 - When you tap on the icon to open it (was in background) there are a few seconds that the app has a white screen until it loads the first view.

**ionic info:**
```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by brandyscarney** [comment]
@ZiFFeL1992 What device was this on?

**Comment by ZiFFeL1992** [comment]
Give me a few days, the issue was on android and I don't have one at the moment. 
iOS seems to be working fine.

**Comment by jguitart** [comment]
Hi. I have a similar problem.
The app simply shows a white screen in android (physical Nexus 4 and emulated nexus 5). And the same with an emulated ios.

**Comment by ZiFFeL1992** [comment]
Here is a demo video: https://drive.google.com/open?id=0BzzwDw5jEO0xenM4cVVXejJVZzg

Running on a Nexus 5x.

**Comment by brandyscarney** [comment]
@ZiFFeL1992 Thanks for the video! I am able to reproduce this. Will investigate.

**Comment by jgw96** [comment]
Note: I can reproduce this issue with the latest version of the ionic conf app, as well as a few of my apps.

**Comment by brandyscarney** [comment]
Hey! This should be fixed with the latest code on both the master and typescript branch. Please clone a fresh copy of the conference app, run `npm install` and then `ionic platform add android` (remove it first if it is already installed). Then, run `ionic run android` and it should be fixed. Note: you may need to remove the conference app from your device if it is already installed. Let me know if you can still reproduce, thanks!

**Comment by gopchi** [comment]
Hi, I am experiencing the same issue when I start it for the first time and also when I have started it, went for example to Instagram, then started the app again and then again white screen for around 3-4 seconds.

I am using Samsung S3 Neo and I also have installed the same plugins which are included in the conf app in Github.

Any suggestions will be very helpful :) Thanks!

**Comment by minawalphonce** [comment]
I still have the same issue 
on Samsung Galaxy s7 and HTC 9x
